services:
    api:
        build: ./api
        ports:
            - 8088:8088
        command: uvicorn main:app --host 0.0.0.0 --port 8088
        depends_on:
            - postgres

    app:
        build: ./app
        ports:
            - 5174:5174
        command: npm run dev
        depends_on:
            - api
    postgres:
        image: postgres:latest
        container_name: postgres_tododb
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: tododb
        volumes:
            - ./db/data:/var/lib/postgresql/data
