FROM python:latest
WORKDIR /api
COPY ./requirements.txt /api/requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY ./ /api
ADD . /api
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8088"]

